apiVersion: v1
data:
  "csi-migration": "false" # csi-migration feature is only available for vSphere 7.0U1
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: openshift-cluster-csi-drivers
